import { StyleSheet } from 'react-native';

import { colors, fonts, radii, spacing } from '../../../lib/theme';
export const slotTerminalStyles = StyleSheet.create({
  fullscreenContainer: {
    backgroundColor: '#000',
  },
  fullscreenOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(10, 10, 15, 0.78)',
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    left: spacing.sm,
    padding: spacing.xs,
    position: 'absolute',
    right: spacing.sm,
    zIndex: 20,
  },
  fullscreenBackButton: {
    alignItems: 'center',
    backgroundColor: colors.bgCard,
    borderRadius: 999,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  fullscreenBackText: {
    color: colors.textPrimary,
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 26,
  },
  fullscreenIdentity: {
    flex: 1,
    minWidth: 0,
  },
  fullscreenTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  fullscreenMeta: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 1,
  },
  fullscreenPill: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  fullscreenPillText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  fullscreenWorkspaceRail: {
    left: spacing.sm,
    position: 'absolute',
    right: spacing.sm,
    zIndex: 19,
  },
  fullscreenWorkspaceRailContent: {
    gap: spacing.xs,
    paddingRight: spacing.md,
  },
  fullscreenNavPill: {
    backgroundColor: 'rgba(18, 18, 28, 0.84)',
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 72,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  fullscreenNavPillDisabled: {
    opacity: 0.44,
  },
  fullscreenNavPillLabel: {
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  fullscreenNavPillValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    marginTop: 1,
  },
  header: {
    backgroundColor: colors.bgSurface,
    borderBottomColor: colors.bgCard,
    borderBottomWidth: 1,
  },
  headerContent: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  terminalCompactHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  backButtonText: {
    color: colors.textPrimary,
    fontSize: 30,
    fontWeight: '600',
    lineHeight: 30,
  },
  terminalIdentity: {
    flex: 1,
    minWidth: 0,
  },
  terminalTarget: {
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    fontWeight: '800',
  },
  terminalMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
  },
  terminalOptionsPanel: {
    gap: spacing.sm,
  },
  terminalProgressPanel: {
    marginTop: spacing.sm,
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  statusText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
  },
  contextText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
  },
  terminalCockpitPanel: {
    backgroundColor: colors.bgCard,
    borderColor: colors.accent + '33',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  terminalCockpitHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  terminalCockpitTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  terminalCockpitTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  terminalCockpitMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  terminalCockpitPill: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  terminalCockpitPillText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  terminalCockpitCompactRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  terminalCockpitCompactMeta: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    color: colors.textMuted,
    flex: 1,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    minWidth: 0,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  terminalCockpitActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  terminalCockpitAction: {
    backgroundColor: colors.accent + '14',
    borderColor: colors.accent + '44',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  terminalCockpitActionText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  terminalCockpitDisabled: {
    opacity: 0.45,
  },
  terminalFocusedArtifactCard: {
    backgroundColor: colors.accent + '12',
    borderColor: colors.accent + '55',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  terminalFocusedArtifactEyebrow: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  terminalFocusedArtifactPath: {
    color: colors.textPrimary,
    fontFamily: fonts.mono,
    fontSize: fonts.sizeSm,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  terminalFocusedArtifactMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
    textTransform: 'uppercase',
  },
  liveBadge: {
    borderRadius: radii.md,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    justifyContent: 'center',
  },
  liveBadgeText: {
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  tailToggle: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  tailToggleActive: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent,
  },
  tailToggleText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  tailToggleTextActive: {
    color: colors.accent,
  },
  lineCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  selectorLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeSm,
    marginRight: spacing.xs,
  },
  selectorChip: {
    borderWidth: 1,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  selectorChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  selectorChipText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    fontWeight: '600',
  },
  selectorChipTextActive: {
    color: '#fff',
  },
  errorBox: {
    backgroundColor: colors.statusFail + '20',
    borderColor: colors.statusFail + '60',
    borderRadius: radii.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  warningBox: {
    backgroundColor: colors.statusWarn + '18',
    borderColor: colors.statusWarn + '55',
    borderRadius: radii.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  warningText: {
    color: colors.statusWarn,
    flex: 1,
    fontSize: fonts.sizeSm,
  },
  warningRetryText: {
    color: colors.statusWarn,
    fontSize: fonts.sizeSm,
    fontWeight: '700',
  },
  errorText: {
    color: colors.statusFail,
    flex: 1,
    fontSize: fonts.sizeSm,
  },
  retryButton: {
    alignSelf: 'center',
  },
  terminalArea: {
    flex: 1,
    backgroundColor: '#000',
  },
  composer: {
    backgroundColor: colors.bgSurface,
    borderTopWidth: 1,
    borderTopColor: colors.bgCard,
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  voicePanel: {
    backgroundColor: colors.bgSurface,
    borderTopWidth: 1,
    borderTopColor: colors.bgCard,
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  voiceComposerRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  voiceInputSurface: {
    flex: 1,
    minWidth: 0,
  },
  voiceInlineMicButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderColor: '#ffffff33',
    borderRadius: radii.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 58,
    width: 48,
  },
  voiceTextInput: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    minHeight: 58,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  voiceTextInputLocked: {
    opacity: 0.72,
  },
  voiceActionStack: {
    gap: spacing.xs,
    width: 72,
  },
  voiceSendButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderColor: colors.accent,
    borderRadius: radii.md,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: spacing.sm,
  },
  voiceCancelButton: {
    alignItems: 'center',
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 22,
    paddingHorizontal: spacing.xs,
  },
  voiceWarningText: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
  },
  voiceProgressText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
  },
  voiceSendText: {
    color: '#fff',
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textAlign: 'center',
  },
  voiceCancelText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    textAlign: 'center',
  },
  floatingVoiceShell: {
    alignItems: 'center',
    height: 68,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.lg,
    width: 68,
  },
  floatingVoicePulse: {
    backgroundColor: colors.statusFail,
    borderRadius: 38,
    height: 76,
    position: 'absolute',
    width: 76,
  },
  floatingVoiceButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderColor: '#ffffff33',
    borderRadius: 31,
    borderWidth: 1,
    height: 62,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    width: 62,
  },
  floatingVoiceButtonBusy: {
    opacity: 0.72,
  },
  controlPanel: {
    alignItems: 'stretch',
    gap: spacing.sm,
  },
  controlLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  controlRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  controlButton: {
    alignItems: 'center',
    backgroundColor: colors.bgCard + '99',
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    flexGrow: 1,
    justifyContent: 'center',
    minWidth: 44,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  interruptButton: {
    backgroundColor: colors.statusFail + '20',
    borderColor: colors.statusFail + '70',
  },
  controlButtonText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    textAlign: 'center',
  },
  tmuxPanel: {
    borderTopColor: colors.bgCard,
    borderTopWidth: 1,
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  tmuxPanelHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  tmuxButton: {
    minWidth: 72,
  },
  tmuxRefreshButton: {
    backgroundColor: colors.bgCard + '99',
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  tmuxRefreshText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  tmuxWindowButton: {
    minWidth: 86,
  },
  tmuxWindowButtonActive: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent,
  },
  tmuxWindowButtonTextActive: {
    color: colors.accent,
  },
  interruptButtonText: {
    color: colors.statusFail,
  },
  sendErrorText: {
    color: colors.statusFail,
    fontSize: fonts.sizeSm,
  },
  disabledButton: {
    opacity: 0.5,
  },
});
