import { StyleSheet } from 'react-native';

import { colors, fonts, radii, spacing } from '../../../lib/theme';
export const workerTerminalStyles = StyleSheet.create({
  container: { backgroundColor: '#000', flex: 1 },
  content: { backgroundColor: '#000', flex: 1 },
  header: {
    alignItems: 'center',
    backgroundColor: colors.bgSurface,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  headerButton: { alignItems: 'center', flexDirection: 'row', minWidth: 48 },
  headerButtonText: { color: colors.accent, fontWeight: '600', fontSize: 13 },
  headerPill: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  headerPillText: { color: colors.textSecondary, fontSize: fonts.sizeXs, fontWeight: '900' },
  tmuxToggleActive: { borderColor: colors.accent, backgroundColor: colors.accent + '22' },
  tmuxToggleTextActive: { color: colors.accent },
  titleBlock: { flex: 1 },
  title: { color: colors.textPrimary, fontWeight: '600', fontSize: 15 },
  subtitle: { color: colors.textMuted, fontFamily: fonts.mono, fontSize: 11 },
  fullscreenOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(10, 10, 15, 0.78)',
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    left: spacing.sm,
    padding: spacing.xs,
    position: 'absolute',
    right: spacing.sm,
    zIndex: 20,
  },
  fullscreenBackButton: {
    alignItems: 'center',
    backgroundColor: colors.bgCard,
    borderRadius: 999,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  fullscreenBackText: {
    color: colors.textPrimary,
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 26,
  },
  fullscreenPill: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  fullscreenPillText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  error: {
    backgroundColor: colors.statusFail + '22',
    color: colors.statusFail,
    padding: spacing.sm,
  },
  terminalArea: { flex: 1 },
  voicePanel: {
    backgroundColor: colors.bgSurface,
    borderTopColor: colors.bgCard,
    borderTopWidth: 1,
    padding: spacing.sm,
  },
  voiceComposerRow: { alignItems: 'stretch', flexDirection: 'row', gap: spacing.sm },
  voiceMicButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: colors.accent,
    borderRadius: radii.lg,
    justifyContent: 'center',
    minWidth: 42,
  },
  voiceInputSurface: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCard,
    borderRadius: radii.lg,
    borderWidth: 1,
    flex: 1,
    minHeight: 48,
  },
  voiceTextInput: {
    color: colors.textPrimary,
    fontSize: 13,
    maxHeight: 104,
    minHeight: 48,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  voiceTextInputLocked: { opacity: 0.7 },
  voiceActionStack: { gap: spacing.xs, justifyContent: 'center', width: 72 },
  voiceSmallButton: {
    alignItems: 'center',
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  voiceSmallButtonText: { color: colors.accent, fontSize: 11, fontWeight: '600' },
  voiceSendButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  voiceSendText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  voiceCancelButton: {
    alignItems: 'center',
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  voiceCancelText: { color: colors.textMuted, fontSize: 11, fontWeight: '600' },
  voiceProgressText: { color: colors.textMuted, fontSize: 11, marginTop: spacing.xs },
  voiceWarningText: { color: colors.statusWarn, fontSize: 11, marginTop: spacing.xs },
  tmuxShortcutPanel: {
    backgroundColor: colors.bgSurface,
    borderTopColor: colors.bgCard,
    borderTopWidth: 1,
    gap: spacing.xs,
    padding: spacing.sm,
  },
  tmuxShortcutTitle: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  tmuxShortcutRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  tmuxShortcutButton: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  tmuxShortcutDanger: {
    backgroundColor: colors.statusFail + '18',
    borderColor: colors.statusFail + '77',
  },
  tmuxShortcutText: { color: colors.textSecondary, fontSize: fonts.sizeXs, fontWeight: '900' },
  tmuxShortcutDangerText: { color: colors.statusFail },
  keyBar: {
    backgroundColor: colors.bgSurface,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    padding: spacing.sm,
  },
  floatingVoiceShell: { position: 'absolute', right: spacing.lg },
  floatingVoicePulse: {
    backgroundColor: colors.accent,
    borderRadius: 24,
    height: 48,
    left: 0,
    position: 'absolute',
    top: 0,
    width: 48,
  },
  floatingVoiceButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  disabledButton: { opacity: 0.5 },
  windowPickerBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    flex: 1,
    justifyContent: 'center',
    padding: spacing.lg,
  },
  windowPickerCard: {
    backgroundColor: colors.bgSurface,
    borderColor: colors.bgCard,
    borderRadius: radii.lg,
    borderWidth: 1,
    maxHeight: '70%',
    padding: spacing.md,
    width: '100%',
  },
  windowPickerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  windowPickerTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  windowPickerClose: {
    color: colors.accent,
    fontSize: 13,
  },
  windowPickerMuted: {
    color: colors.textMuted,
    padding: spacing.sm,
    textAlign: 'center',
  },
  windowPickerError: {
    color: colors.statusFail,
    padding: spacing.sm,
    textAlign: 'center',
  },
  windowPickerList: {
    marginTop: spacing.xs,
  },
  windowPickerItem: {
    backgroundColor: colors.bgBase,
    borderColor: colors.bgCard,
    borderRadius: radii.lg,
    borderWidth: 1,
    marginBottom: spacing.xs,
    padding: spacing.md,
  },
  windowPickerItemActive: {
    borderColor: colors.statusOk,
  },
  windowPickerItemTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.mono,
    fontSize: 14,
    fontWeight: '600',
  },
  windowPickerItemMeta: {
    color: colors.textMuted,
    fontFamily: fonts.mono,
    fontSize: 11,
    marginTop: 2,
  },
});
