import { StyleSheet } from 'react-native';

import { colors, fonts, radii, spacing } from '../../../lib/theme';
export const decisionWorkspaceStyles = StyleSheet.create({
  center: { justifyContent: 'center', alignItems: 'center', gap: spacing.lg },
  scrollContent: { padding: spacing.xl, paddingBottom: spacing.xxxl * 2 },
  stickyWorkspaceNav: {
    backgroundColor: colors.bgSurface,
    borderBottomColor: colors.bgCard,
    borderBottomWidth: 1,
    left: 0,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 20,
  },
  headerCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.lg,
    padding: spacing.xl,
    marginBottom: spacing.xl,
    borderLeftWidth: 4,
  },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  kindBadge: { paddingHorizontal: spacing.md, paddingVertical: spacing.xs, borderRadius: 4 },
  kindText: { fontSize: fonts.sizeSm, fontWeight: '800', textTransform: 'uppercase' },
  ageText: { color: colors.textMuted, fontSize: fonts.sizeXs },
  title: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXl,
    fontWeight: '800',
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  metaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginTop: spacing.lg },
  metaItem: { flexBasis: '48%', flexGrow: 1 },
  metaLabel: { color: colors.textMuted, fontSize: fonts.sizeXs, marginBottom: spacing.xs },
  metaValue: { color: colors.textPrimary, fontSize: fonts.sizeSm, fontWeight: '600' },
  workspaceCockpitPanel: {
    backgroundColor: colors.bgCard,
    borderColor: colors.accent + '33',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginBottom: spacing.xl,
    padding: spacing.sm,
  },
  beforeAfterPriorityPanel: {
    backgroundColor: colors.accent + '10',
    borderColor: colors.accent + '44',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginBottom: spacing.xl,
    padding: spacing.sm,
  },
  beforeAfterPriorityActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  beforeAfterPriorityCopy: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  beforeAfterPriorityButton: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  beforeAfterPriorityButtonText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  beforeAfterPriorityRail: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  workspaceCockpitHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  workspaceCockpitTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  workspaceCockpitTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceCockpitMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
  },
  workspaceCockpitRail: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  workspaceCockpitTile: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    minWidth: 104,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  workspaceCockpitTileLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceCockpitTileValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  workspaceCockpitTileHint: {
    color: colors.textMuted,
    fontSize: 10,
    marginTop: 2,
    maxWidth: 110,
  },
  workspaceCockpitAction: {
    backgroundColor: colors.accent + '14',
    borderColor: colors.accent + '44',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  workspaceCockpitActionPrimary: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
  },
  workspaceCockpitActionText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  workspaceCockpitActionTextPrimary: {
    color: colors.textPrimary,
  },
  workspaceCockpitDisabled: {
    opacity: 0.45,
  },
  focusedArtifactCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.statusWarn + '66',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    marginBottom: spacing.xl,
    padding: spacing.md,
  },
  focusedArtifactHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  focusedArtifactTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  focusedArtifactEyebrow: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  focusedArtifactPath: {
    color: colors.textPrimary,
    fontFamily: 'Menlo',
    fontSize: fonts.sizeSm,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  focusedArtifactMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
  },
  focusedArtifactActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  errorText: { color: colors.statusFail, marginBottom: spacing.lg },
  section: { marginBottom: spacing.xl },
  recipeEvidenceHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  recipeEvidenceTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  recipeEvidenceMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  recipeEvidenceOpenButton: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  recipeEvidenceOpenText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  recipePairPreview: {
    backgroundColor: colors.bgCard,
    borderColor: colors.accent + '24',
    borderRadius: radii.lg,
    borderWidth: 1,
    marginBottom: spacing.md,
    padding: spacing.xs,
  },
  recipePreviewStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  recipePreviewTile: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    padding: spacing.xs,
    width: 92,
  },
  recipePreviewImage: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.sm,
    height: 54,
    width: '100%',
  },
  recipePreviewDocument: {
    alignItems: 'center',
    backgroundColor: colors.bgInput,
    borderRadius: radii.sm,
    height: 54,
    justifyContent: 'center',
    width: '100%',
  },
  recipePreviewKind: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  recipePreviewPath: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  sectionTitle: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: spacing.md,
  },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginBottom: spacing.md },
  signalChip: {
    borderWidth: 1,
    borderRadius: radii.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.bgCard,
  },
  signalChipPressable: {
    backgroundColor: colors.bgCardHover,
  },
  signalLabel: { fontSize: fonts.sizeXs, fontWeight: '800', textTransform: 'uppercase' },
  signalValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  signalValue: { color: colors.textPrimary, fontSize: fonts.sizeSm },
  signalArrow: { fontSize: fonts.sizeMd, fontWeight: '900' },
  bullet: { color: colors.textPrimary, fontSize: fonts.sizeSm, marginBottom: spacing.sm },
  reportCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  reportTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  reportBody: {
    color: colors.textSecondary,
    fontFamily: 'Menlo',
    fontSize: fonts.sizeSm,
    lineHeight: 18,
  },
  terminalButton: {
    backgroundColor: colors.accent + '25',
    borderRadius: radii.md,
    padding: spacing.lg,
  },
  terminalButtonText: { color: colors.accent, fontSize: fonts.sizeMd, fontWeight: '800' },
  actionButton: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  actionText: { color: '#fff', fontSize: fonts.sizeMd, fontWeight: '800' },
  actionDescription: { color: '#ffffffcc', fontSize: fonts.sizeSm, marginTop: spacing.sm },
  safetyCard: {
    backgroundColor: colors.statusWarn + '18',
    borderColor: colors.statusWarn + '55',
    borderWidth: 1,
    borderRadius: radii.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  resolvedDecisionCard: {
    backgroundColor: colors.statusOk + '18',
    borderColor: colors.statusOk + '55',
    borderWidth: 1,
    borderRadius: radii.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  safetyTitle: {
    color: colors.statusWarn,
    fontSize: fonts.sizeSm,
    fontWeight: '800',
    marginBottom: spacing.xs,
  },
  safetyText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    lineHeight: 18,
  },
  secondaryButton: {
    backgroundColor: colors.accent + '25',
    borderRadius: radii.md,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
  },
  secondaryButtonText: { color: colors.accent, fontSize: fonts.sizeSm, fontWeight: '700' },
});
