import { StyleSheet } from 'react-native';

import { colors, fonts, radii, spacing } from '../../../lib/theme';

export const visualReviewStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bgBase },
  content: { padding: spacing.xl, gap: spacing.xl, paddingBottom: spacing.xxxl * 2 },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xxl },
  card: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.lg,
    padding: spacing.lg,
    gap: spacing.md,
  },
  eyebrow: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  title: { color: colors.textPrimary, fontSize: fonts.sizeXl, fontWeight: '700' },
  body: { color: colors.textPrimary, fontSize: fonts.sizeMd },
  muted: { color: colors.textSecondary, fontSize: fonts.sizeSm },
  error: { color: colors.statusFail, fontSize: fonts.sizeMd },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, alignItems: 'center' },
  chip: {
    minHeight: 40,
    paddingHorizontal: spacing.lg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.bgCardHover,
    backgroundColor: colors.bgSurface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  chipActive: { borderColor: colors.accent, backgroundColor: colors.accentDim },
  chipText: { color: colors.textPrimary, fontSize: fonts.sizeSm, fontWeight: '600' },
  chipCount: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '700',
    backgroundColor: colors.accent,
    borderRadius: 8,
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
  },
  button: {
    minHeight: 44,
    paddingHorizontal: spacing.xl,
    borderRadius: radii.md,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonSecondary: {
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.bgCardHover,
  },
  buttonDanger: {
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.statusFail,
  },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: colors.textPrimary, fontSize: fonts.sizeMd, fontWeight: '700' },
  input: {
    minHeight: 72,
    borderRadius: radii.md,
    backgroundColor: colors.bgInput,
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    padding: spacing.lg,
    textAlignVertical: 'top',
  },
  canvasViewport: { alignSelf: 'center', backgroundColor: colors.bgSurface },
  point: {
    position: 'absolute',
    width: 32,
    height: 32,
    marginLeft: -16,
    marginTop: -16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  area: { position: 'absolute', borderWidth: 2, borderRadius: radii.sm },
  areaBadge: {
    position: 'absolute',
    top: -12,
    left: -12,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerSelected: { borderWidth: 4, borderColor: '#ffffff' },
  markerText: { color: '#ffffff', fontSize: fonts.sizeSm, fontWeight: '800' },
  swatch: { width: 40, height: 40, borderRadius: 20, borderWidth: 2, borderColor: 'transparent' },
  swatchActive: { borderColor: '#ffffff' },
  nudgeGrid: { flexDirection: 'row', gap: spacing.md, flexWrap: 'wrap' },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    borderRadius: radii.md,
    backgroundColor: colors.bgSurface,
  },
  listItemActive: { borderWidth: 1, borderColor: colors.accent },
  dot: { width: 14, height: 14, borderRadius: 7 },
  statusAccepted: { color: colors.statusOk },
  statusPending: { color: colors.statusWarn },
  statusFailed: { color: colors.statusFail },
});
