// signal.ts — Worker signal file schema for push-based completion detection.
// Workers write SIGNAL.json to their task directory; task-watcher detects it.

import type {
  AgentRole,
  WorkerTerminalDisposition,
  WorkerTerminalEvidence,
} from '../contracts/index.js';

export interface WorkerSignal {
  role?: AgentRole;
  contextId?: string;
  /** Opaque identity generated by `mark start` and retained for this attempt. */
  attemptId?: string;
  status: 'running' | 'blocked' | 'complete' | 'failed' | 'done';
  outcome?: 'success' | 'failure' | 'partial';
  disposition?: WorkerTerminalDisposition;
  evidence?: WorkerTerminalEvidence;
  artifactWaivers?: WorkerSignalArtifactWaivers;
  checklistTiming?: WorkerSignalChecklistTiming;
  step?: string; // current step name
  reason?: string; // why blocked/failed
  prNumber?: number; // if worker created a PR
  /** The worker completed a trivial update-branch task that does not need self-review. */
  needsSelfReview?: boolean;
  timestamp: string;
}

export type WorkerSignalStatus = WorkerSignal['status'];

// One entry per status, so adding a member to the union fails to compile here
// until someone decides whether it is terminal.
const WORKER_SIGNAL_STATUS_IS_TERMINAL = {
  running: false,
  blocked: true,
  complete: true,
  failed: true,
  done: true,
} satisfies Record<WorkerSignalStatus, boolean>;

/**
 * A status the worker cannot move past. `done` is an accepted terminal alias of
 * `complete`. Takes a plain string so readers of an untyped SIGNAL.json can ask
 * without first narrowing; an unknown status is not terminal.
 */
export function isTerminalWorkerSignalStatus(status: string | null | undefined): boolean {
  return (
    status !== null &&
    status !== undefined &&
    Object.hasOwn(WORKER_SIGNAL_STATUS_IS_TERMINAL, status) &&
    WORKER_SIGNAL_STATUS_IS_TERMINAL[status as WorkerSignalStatus]
  );
}

export function isTerminalWorkerSignal(
  signal: WorkerSignal | Pick<WorkerSignal, 'status'>,
): boolean {
  return isTerminalWorkerSignalStatus(signal.status);
}

export interface WorkerSignalArtifactWaivers {
  /** The worker explicitly completed with `./mark ... --skip-learnings`. */
  learnings?: boolean;
}

export interface WorkerSignalChecklistTiming {
  schemaVersion: 1;
  /**
   * Stable identifier for the checklist file or prompt section when known
   * (for example `TASK.md` or `CHECKLIST.md`).
   */
  source?: string;
  /**
   * Append-only event history for checklist items the worker has marked done.
   * Consumers derive deltas from the event order and timestamps.
   */
  events: WorkerSignalChecklistEvent[];
}

export interface WorkerSignalChecklistEvent {
  /** 1-based checklist step number, matching the worker-facing `mark N` command. */
  stepNumber: number;
  /** The step name (`checklistStepName` of the row), copied so the event survives a later markdown edit. */
  label: string;
  /** UTC ISO8601 timestamp when the item changed from unchecked to checked. */
  checkedAt: string;
}

export interface WorkerSignalChecklistStepDuration {
  stepNumber: number;
  label: string;
  durationMs: number;
}

/**
 * Derive stable per-step durations from append-only checklist marks.
 * The first step uses the attempt start when available; older callers without
 * a start timestamp retain the previous zero-duration behavior.
 */
export function deriveChecklistStepDurations(
  timing: WorkerSignalChecklistTiming | null | undefined,
  startedAt?: string | null,
): WorkerSignalChecklistStepDuration[] {
  if (!timing?.events.length) return [];
  const events = [...timing.events].sort((a, b) => a.checkedAt.localeCompare(b.checkedAt));
  const startedMs = startedAt ? Date.parse(startedAt) : Number.NaN;
  let previousMs = Number.isFinite(startedMs) ? startedMs : null;
  return events.map((event) => {
    const checkedMs = Date.parse(event.checkedAt);
    const durationMs =
      previousMs != null && Number.isFinite(checkedMs) ? Math.max(0, checkedMs - previousMs) : 0;
    if (Number.isFinite(checkedMs)) previousMs = checkedMs;
    return { stepNumber: event.stepNumber, label: event.label, durationMs };
  });
}

/** Structured probe result for operator "check SIGNAL.json" flows. */
export type WorkerSignalProbeCode =
  | 'ready'
  | 'no_slot'
  | 'missing_path'
  | 'missing'
  | 'invalid_json'
  | 'invalid_schema'
  | 'non_terminal'
  | 'context_mismatch'
  | 'stale'
  | 'artifact_contract'
  | 'terminal_contract_infrastructure';

export interface WorkerSignalProbeResult {
  ok: boolean;
  code: WorkerSignalProbeCode;
  message: string;
  /** Repo-relative signal path when known (for example `.task/.../SIGNAL.json`). */
  signalFile?: string | null;
  status?: string;
  signal?: WorkerSignal;
}
