export { type AdapterRegistry, createAdapterRegistry, defineAdapter } from './registry.js';
export {
  ADAPTER_SDK_VERSION,
  type AdapterActions,
  type AdapterCdpTarget,
  type AdapterConsoleFiles,
  type AdapterDetect,
  type AdapterDevServer,
  type AdapterDevServerStop,
  type AdapterDiagnostics,
  type AdapterFailurePatterns,
  type AdapterFlags,
  type AdapterHarness,
  type AdapterHarnessLeaf,
  type AdapterHarnessVerify,
  type AdapterHints,
  type AdapterLaunchContext,
  type AdapterLogSource,
  type AdapterRecording,
  type AdapterRuntimeContextSpec,
  type AdapterRuntimeStatus,
  type AdapterSdkVersion,
  type AdapterUiHarness,
  type AdapterUiTransport,
  type CommandEventStream,
  type HealBoundViolation,
  type HealMutation,
  type HealPolicy,
  type HealState,
  type NativeUiTransport,
  type NativeUiTransportOptions,
  type PlatformAdapter,
} from './types.js';
