import { StyleSheet } from 'react-native';

import { colors, fonts, radii, spacing } from '../../../lib/theme';
export const runDetailStyles = StyleSheet.create({
  center: { justifyContent: 'center', alignItems: 'center' },
  backFallbackButton: {
    backgroundColor: colors.accent + '20',
    borderRadius: radii.md,
    marginTop: spacing.lg,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
  },
  backFallbackText: {
    color: colors.accent,
    fontSize: fonts.sizeSm,
    fontWeight: '800',
  },
  scrollContent: { padding: spacing.xl, paddingBottom: spacing.xxxl * 2 },
  stickyWorkspaceNav: {
    backgroundColor: colors.bgSurface,
    borderBottomColor: colors.bgCard,
    borderBottomWidth: 1,
    left: 0,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 20,
  },
  headerCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.lg,
    padding: spacing.xl,
    marginBottom: spacing.xl,
  },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  flowBadge: { paddingHorizontal: spacing.md, paddingVertical: spacing.xs, borderRadius: 4 },
  flowText: { fontSize: fonts.sizeSm, fontWeight: '600' },
  statusBadge: { paddingHorizontal: spacing.md, paddingVertical: spacing.xs, borderRadius: 4 },
  statusText: { fontSize: fonts.sizeSm, fontWeight: '600' },
  ticketText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeLg,
    fontWeight: '700',
    marginTop: spacing.lg,
  },
  section: { marginBottom: spacing.xl },
  sectionTitle: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: spacing.md,
  },
  workspaceCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    marginBottom: spacing.xl,
    padding: spacing.lg,
  },
  focusedArtifactCard: {
    backgroundColor: colors.accent + '12',
    borderColor: colors.accent + '55',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginBottom: spacing.xl,
    padding: spacing.sm,
  },
  focusedArtifactTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  focusedArtifactEyebrow: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  focusedArtifactPath: {
    color: colors.textPrimary,
    fontFamily: fonts.mono,
    fontSize: fonts.sizeSm,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  focusedArtifactMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
    textTransform: 'uppercase',
  },
  focusedArtifactPrimaryButton: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  focusedArtifactPrimaryText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  workspaceHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  workspaceBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  workspaceBadgeText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceRunMeta: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fonts.sizeXs,
    textAlign: 'right',
    textTransform: 'uppercase',
  },
  workspaceGateButton: {
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  workspaceGateButtonText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  workspaceTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    fontWeight: '900',
  },
  workspaceSummary: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    lineHeight: 20,
  },
  runBeforeAfterPriorityPanel: {
    backgroundColor: colors.accent + '10',
    borderColor: colors.accent + '44',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  runBeforeAfterPriorityActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  runBeforeAfterPriorityCopy: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  runBeforeAfterPriorityButton: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  runBeforeAfterPriorityButtonText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  runBeforeAfterPriorityRail: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  workspaceSignalRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  workspaceSignalChip: {
    backgroundColor: colors.accent + '12',
    borderColor: colors.accent + '33',
    borderRadius: radii.md,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  workspaceSignalLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  workspaceSignalValue: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    marginTop: 2,
    maxWidth: 120,
  },
  workspaceEvidenceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  workspaceEvidenceChip: {
    backgroundColor: colors.accent + '12',
    borderColor: colors.accent + '44',
    borderRadius: 999,
    borderWidth: 1,
    maxWidth: 160,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  workspaceEvidenceChipText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  workspacePreviewStrip: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  workspacePreviewButton: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  workspacePreviewImage: {
    backgroundColor: colors.bgInput,
    height: 64,
    width: 88,
  },
  workspacePreviewDocumentTile: {
    alignItems: 'center',
    backgroundColor: colors.bgInput,
    gap: spacing.xs,
    height: 64,
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    width: 96,
  },
  workspacePreviewDocumentKind: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  workspacePreviewDocumentPath: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    lineHeight: 14,
    textAlign: 'center',
  },
  workspaceGateRailPanel: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  workspaceGateRailHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  workspaceGateRailTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceGateRailMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  workspaceGateRail: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  workspaceGateRailCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.xs,
    minWidth: 184,
    padding: spacing.md,
  },
  workspaceGateRailCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  workspaceGateRailLabel: {
    flex: 1,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceGateRailStatus: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  workspaceGateRailCardTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    lineHeight: 16,
  },
  workspaceGateRailMetrics: {
    gap: 2,
  },
  workspaceGateRailMetric: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
  },
  workspaceGateRailActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  workspaceGateRailAction: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.sm,
    borderWidth: 1,
    minWidth: 72,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  workspaceGateRailActionLabel: {
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceGateRailActionValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    marginTop: 1,
  },
  cockpitPanel: {
    backgroundColor: colors.bgInput,
    borderColor: colors.accent + '30',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  cockpitHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  cockpitTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  cockpitMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
    textTransform: 'uppercase',
  },
  cockpitTerminalButton: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  cockpitTerminalText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  cockpitRail: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  cockpitTile: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    minWidth: 116,
    padding: spacing.md,
  },
  cockpitTileDisabled: {
    opacity: 0.45,
  },
  cockpitTileLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  cockpitTileValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
    marginTop: spacing.xs,
  },
  cockpitTileHint: {
    color: colors.textMuted,
    fontSize: 10,
    marginTop: 2,
    maxWidth: 110,
  },
  workspaceRecipeContext: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
  },
  stepCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    padding: spacing.lg,
    marginBottom: spacing.sm,
  },
  stepCardExpanded: {
    borderWidth: 1,
    borderColor: colors.accent + '55',
  },
  stepLeft: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: spacing.md, minWidth: 0 },
  stepIcon: { fontSize: fonts.sizeMd, width: 20 },
  stepTitleWrap: { flex: 1, minWidth: 0 },
  stepName: { color: colors.textPrimary, fontSize: fonts.sizeMd, fontWeight: '700' },
  stepDetailPreview: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
  },
  stepRight: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: spacing.xs,
    marginLeft: spacing.sm,
  },
  stepDurationText: { color: colors.textMuted, fontSize: fonts.sizeSm },
  expandGlyph: {
    color: colors.accent,
    fontSize: fonts.sizeLg,
    fontWeight: '800',
  },
  stepExpandedBody: {
    borderTopWidth: 1,
    borderTopColor: colors.bgInput,
    gap: spacing.md,
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
  },
  stepReplayPanel: {
    backgroundColor: colors.statusWarn + '12',
    borderColor: colors.statusWarn + '44',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  stepReplayTextWrap: {
    gap: spacing.xs,
  },
  stepReplayTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  stepReplayHint: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    lineHeight: 17,
  },
  stepReplayActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  stepReplayButton: {
    backgroundColor: colors.statusWarn + '22',
    borderColor: colors.statusWarn + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  stepReplayButtonSecondary: {
    backgroundColor: colors.bgInput,
  },
  stepReplayButtonDisabled: {
    opacity: 0.45,
  },
  stepReplayButtonText: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  stepDiagnosePanel: {
    backgroundColor: colors.accent + '12',
    borderColor: colors.accent + '44',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  stepDiagnoseButton: {
    alignSelf: 'flex-start',
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  stepDiagnoseButtonText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  stepMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  stepMetaItem: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.sm,
    padding: spacing.md,
    width: '47%',
  },
  stepMetaLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginBottom: spacing.xs,
    textTransform: 'uppercase',
  },
  stepMetaValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '700',
  },
  stepBlock: {
    gap: spacing.sm,
  },
  stepBlockTitle: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  stepArtifactButton: {
    alignItems: 'center',
    backgroundColor: colors.accent + '18',
    borderRadius: radii.sm,
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  stepArtifact: {
    color: colors.accent,
    flex: 1,
    fontSize: fonts.sizeXs,
    fontWeight: '700',
  },
  stepArtifactOpen: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  stepJson: {
    color: colors.textSecondary,
    backgroundColor: colors.bgInput,
    borderRadius: radii.md,
    fontFamily: 'Menlo',
    fontSize: fonts.sizeXs,
    lineHeight: 16,
    padding: spacing.md,
  },
  decisionCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderWidth: 1,
    borderLeftWidth: 3,
    borderRadius: radii.md,
    gap: spacing.sm,
    padding: spacing.lg,
    marginBottom: spacing.sm,
  },
  decisionTypeBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  decisionTypeText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  decisionOpenText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  decisionTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  decisionSummaryText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    lineHeight: 19,
  },
  decisionSignalRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  decisionSignalChip: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.sm,
    borderWidth: 1,
    maxWidth: '48%',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  decisionSignalLabel: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  decisionSignalValue: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    marginTop: 2,
  },
  metricsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  metricItem: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    padding: spacing.lg,
    minWidth: 100,
    alignItems: 'center',
  },
  metricLabel: { color: colors.textMuted, fontSize: fonts.sizeXs, marginBottom: spacing.xs },
  metricValue: { color: colors.textPrimary, fontSize: fonts.sizeMd, fontWeight: '600' },
  artifactCountBadge: {
    backgroundColor: colors.accent + '30',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 4,
  },
  artifactCountText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '600',
  },
  recipeSummary: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  recipeRunStrip: {
    marginBottom: spacing.md,
  },
  recipeRunCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgInput,
    borderRadius: radii.md,
    borderWidth: 1,
    marginRight: spacing.sm,
    minWidth: 150,
    padding: spacing.md,
  },
  recipeRunCardActive: {
    backgroundColor: colors.accent + '18',
    borderColor: colors.accent,
  },
  recipeRunLabel: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  recipeRunLabelActive: {
    color: colors.accent,
  },
  recipeRunMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
    textTransform: 'uppercase',
  },
  recipeContextHint: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    lineHeight: 17,
    marginBottom: spacing.md,
  },
  recipePairPreview: {
    marginBottom: spacing.md,
  },
  thumbStrip: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  artifactThumb: {
    width: 64,
    height: 48,
    borderRadius: radii.sm,
    backgroundColor: colors.bgInput,
  },
  recipeArtifactTile: {
    alignItems: 'center',
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.sm,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    width: 78,
  },
  recipeArtifactTileKind: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  recipeArtifactTilePath: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    marginTop: 2,
    textAlign: 'center',
  },
  viewAllButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: colors.accent + '20',
    borderRadius: radii.sm,
  },
  viewAllText: {
    color: colors.accent,
    fontSize: fonts.sizeSm,
    fontWeight: '600',
  },
  recipeControlsWrap: {
    marginTop: spacing.md,
  },
  terminalButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.accent + '20',
    borderRadius: radii.md,
  },
  terminalButtonText: {
    color: colors.accent,
    fontSize: fonts.sizeSm,
    fontWeight: '700',
  },
  errorText: {
    color: colors.statusFail,
    fontSize: fonts.sizeSm,
    marginBottom: spacing.xl,
  },
});
