import type { BacklogItem, WorkGraphProjection, WorkNodeStatus } from '@farmslot/protocol';

const NOW = '2026-06-29T08:00:00.000Z';
const GRAPH_ID = 'wg_demo_cross_project_epic';
const GRAPH_PROJECT = 'portfolio-epic';

interface DemoBacklogSpec {
  id: string;
  nodeId: string;
  project: string;
  title: string;
  status: BacklogItem['status'];
  nodeStatus: WorkNodeStatus;
  notes: string;
  tags: string[];
  familyId?: string;
  rootRunId?: string;
  latestRunId?: string;
  baseRef?: string;
  upstreamBaseNodeIds?: string[];
  waitingOn?: WorkGraphProjection['nodes'][number]['waitingOn'];
}

const SPECS: DemoBacklogSpec[] = [
  {
    id: 'bl_demo_refine_requirement',
    nodeId: 'wn_refine_requirement',
    project: 'roadmap',
    title: 'Refine raw idea into backlog-ready epic plan',
    status: 'done',
    nodeStatus: 'succeeded',
    notes:
      'Start from a rough idea, define acceptance criteria, then split the work into independent backlog items with explicit dependencies.',
    tags: ['roadmap', 'refinement', 'epic-demo'],
    familyId: 'fam_demo_refine_requirement',
    rootRunId: 'run_demo_refine_root',
    latestRunId: 'run_demo_refine_review',
  },
  {
    id: 'bl_demo_shared_contract',
    nodeId: 'wn_shared_contract',
    project: 'platform-protocol',
    title: 'Define shared graph/backlog contract',
    status: 'done',
    nodeStatus: 'succeeded',
    notes:
      'Defines the shared fields used by backlog items, graph nodes, dependency edges, tags, gates, and run-family links.',
    tags: ['contract', 'protocol', 'epic-demo'],
    familyId: 'fam_demo_shared_contract',
    rootRunId: 'run_demo_contract_root',
    latestRunId: 'run_demo_contract_ci',
    baseRef: 'main@3c76f96',
    upstreamBaseNodeIds: ['wn_refine_requirement'],
  },
  {
    id: 'bl_demo_gateway_projection',
    nodeId: 'wn_gateway_projection',
    project: 'gateway',
    title: 'Expose backlog dependency graph projection',
    status: 'running',
    nodeStatus: 'running',
    notes:
      'Implements the API/projection that downstream UIs and tools consume. Other work may start from the contract, but must rebase after this lands.',
    tags: ['gateway', 'projection', 'epic-demo'],
    familyId: 'fam_demo_gateway_projection',
    rootRunId: 'run_demo_gateway_root',
    latestRunId: 'run_demo_gateway_tests',
    baseRef: 'contract-graph-v1',
    upstreamBaseNodeIds: ['wn_shared_contract'],
  },
  {
    id: 'bl_demo_ui_visualization',
    nodeId: 'wn_ui_visualization',
    project: 'command-center',
    title: 'Build read-only graph visualization',
    status: 'ready',
    nodeStatus: 'ready',
    notes:
      'Can start from the shared contract and fixture data. Completion is blocked until the gateway projection merges and this branch rebases onto it.',
    tags: ['ui', 'visualization', 'epic-demo'],
    familyId: 'fam_demo_ui_visualization',
    rootRunId: 'run_demo_ui_root',
    latestRunId: 'run_demo_ui_visual_review',
    baseRef: 'contract-graph-v1',
    upstreamBaseNodeIds: ['wn_shared_contract', 'wn_gateway_projection'],
    waitingOn: [
      {
        kind: 'upstream',
        edgeId: 'we_gateway_to_ui_rebase',
        upstreamNodeId: 'wn_gateway_projection',
        detail: 'Can start now, but must rebase onto the gateway projection before completion.',
      },
    ],
  },
  {
    id: 'bl_demo_cli_import',
    nodeId: 'wn_cli_import',
    project: 'cli',
    title: 'Import markdown backlog specs into a graph',
    status: 'queued',
    nodeStatus: 'queued',
    notes:
      'Cannot start until the gateway projection exists, because it calls the graph API to link backlog items and dependency edges.',
    tags: ['cli', 'import', 'epic-demo'],
    familyId: 'fam_demo_cli_import',
    rootRunId: 'run_demo_cli_root',
    baseRef: 'gateway-projection',
    upstreamBaseNodeIds: ['wn_gateway_projection'],
  },
  {
    id: 'bl_demo_companion_status',
    nodeId: 'wn_companion_status',
    project: 'companion-app',
    title: 'Show epic dependency status on mobile companion',
    status: 'ready',
    nodeStatus: 'ready',
    notes:
      'Can start against the shared contract and mock data. It cannot complete until the real gateway projection is merged and rebased.',
    tags: ['mobile', 'status', 'epic-demo'],
    familyId: 'fam_demo_companion_status',
    rootRunId: 'run_demo_companion_root',
    baseRef: 'contract-graph-v1',
    upstreamBaseNodeIds: ['wn_shared_contract', 'wn_gateway_projection'],
    waitingOn: [
      {
        kind: 'upstream',
        edgeId: 'we_gateway_to_companion_rebase',
        upstreamNodeId: 'wn_gateway_projection',
        detail: 'Can start now, but must rebase onto the gateway projection before completion.',
      },
    ],
  },
  {
    id: 'bl_demo_authoring_controls',
    nodeId: 'wn_authoring_controls',
    project: 'command-center',
    title: 'Add graph authoring controls',
    status: 'needs-attention',
    nodeStatus: 'gated',
    notes:
      'Mutating create/edit/refine actions are held behind a UX review gate after read-only visualization is validated.',
    tags: ['ui', 'authoring', 'human-gate', 'epic-demo'],
    familyId: 'fam_demo_authoring_controls',
    rootRunId: 'run_demo_authoring_root',
    latestRunId: 'run_demo_authoring_review',
    baseRef: 'feature/graph-visualization',
    upstreamBaseNodeIds: ['wn_ui_visualization'],
    waitingOn: [
      {
        kind: 'manual-gate',
        edgeId: 'we_ui_to_authoring_ux_gate',
        upstreamNodeId: 'wn_ui_visualization',
        detail: 'Needs human UX approval before write actions are enabled.',
      },
    ],
  },
  {
    id: 'bl_demo_e2e_validation',
    nodeId: 'wn_e2e_validation',
    project: 'validation-recipes',
    title: 'Validate cross-project graph workflow end to end',
    status: 'candidate',
    nodeStatus: 'waiting',
    notes:
      'Recipe proves import, visualization, authoring, companion status, dependency waits, rebase gates, and dispatch family links.',
    tags: ['validation', 'recipe', 'epic-demo'],
    upstreamBaseNodeIds: ['wn_cli_import', 'wn_authoring_controls', 'wn_companion_status'],
    waitingOn: [
      {
        kind: 'upstream',
        edgeId: 'we_cli_to_e2e',
        upstreamNodeId: 'wn_cli_import',
        detail: 'CLI import must finish before full workflow validation.',
      },
      {
        kind: 'manual-gate',
        edgeId: 'we_authoring_to_e2e',
        upstreamNodeId: 'wn_authoring_controls',
        detail: 'Authoring controls must pass UX gate before E2E validation.',
      },
    ],
  },
  {
    id: 'bl_demo_docs',
    nodeId: 'wn_docs',
    project: 'docs',
    title: 'Document graph semantics with screenshots',
    status: 'ready',
    nodeStatus: 'ready',
    notes:
      'Docs explain backlog nodes, dependency edges, start blockers, completion/rebase blockers, human gates, and run-family metadata.',
    tags: ['docs', 'screenshots', 'epic-demo'],
    familyId: 'fam_demo_docs',
    rootRunId: 'run_demo_docs_root',
    latestRunId: 'run_demo_docs_capture',
    baseRef: 'feature/work-graph-visualization',
  },
  {
    id: 'bl_demo_release',
    nodeId: 'wn_release',
    project: 'release-ops',
    title: 'Roll out epic after evidence and gates pass',
    status: 'candidate',
    nodeStatus: 'waiting',
    notes:
      'Final release waits for E2E evidence and docs approval. It is a backlog item because release work has its own acceptance criteria.',
    tags: ['release', 'rollout', 'epic-demo'],
    waitingOn: [
      {
        kind: 'manual-gate',
        edgeId: 'we_e2e_to_release',
        upstreamNodeId: 'wn_e2e_validation',
        detail: 'Operator must accept E2E screenshots and validation results.',
      },
      {
        kind: 'manual-gate',
        edgeId: 'we_docs_to_release',
        upstreamNodeId: 'wn_docs',
        detail: 'Docs/screenshots must be accepted for release notes.',
      },
    ],
  },
];

const REFERENCE_NODES: WorkGraphProjection['nodes'] = [
  {
    id: 'wn_external_core_pr',
    graphId: GRAPH_ID,
    kind: 'reference',
    reference: {
      kind: 'github-pr',
      title: 'External core controller PR merged',
      ref: 'metamask/core#1842',
      url: 'https://github.com/MetaMask/core/pull/1842',
      project: 'metamask-core',
      owner: 'external-team',
      status: 'pending',
      evidence: 'Client work can start from mocks, but release completion waits for this PR.',
      labels: ['external', 'pr', 'release-blocker'],
      updatedAt: NOW,
    },
    tags: ['external', 'release-blocker'],
    status: 'waiting',
    waitingOn: [
      {
        kind: 'upstream',
        detail: 'Waiting on github-pr reference metamask/core#1842',
      },
    ],
    updatedAt: NOW,
  },
  {
    id: 'wn_package_publish',
    graphId: GRAPH_ID,
    kind: 'reference',
    reference: {
      kind: 'package-release',
      title: 'Shared package version published',
      ref: '@metamask/controller@12.4.0',
      project: 'npm',
      owner: 'release-ops',
      status: 'satisfied',
      evidence: 'Package publish is recorded as an external milestone, not Farmslot-owned work.',
      labels: ['external', 'package', 'milestone'],
      updatedAt: NOW,
    },
    tags: ['external', 'package'],
    status: 'succeeded',
    waitingOn: [],
    updatedAt: NOW,
  },
];

export const mockWorkGraphBacklogItems: BacklogItem[] = SPECS.map((spec) => ({
  id: spec.id,
  project: spec.project,
  title: spec.title,
  sourceKind: 'manual',
  sourceRef: spec.id,
  flowType: 'dev',
  status: spec.status,
  notes: spec.notes,
  tags: spec.tags,
  roadmapItemId: 'roadmap_cross_project_dependency_epic',
  specPath: `~/dev/roadmap/${spec.project}/${spec.id}.md`,
  workGraphId: GRAPH_ID,
  workNodeId: spec.nodeId,
  priority: 50,
  autoDispatch: false,
  createdAt: NOW,
  updatedAt: NOW,
}));

export const mockWorkGraphs: WorkGraphProjection[] = [
  {
    graph: {
      id: GRAPH_ID,
      version: 1,
      project: GRAPH_PROJECT,
      title: 'Hypothetical cross-project epic: ordered backlog dependencies and rebase gates',
      source: { kind: 'manual', ref: 'roadmap_cross_project_dependency_epic' },
      tags: ['cross-project', 'epic-demo', 'rebase-gates', 'human-gates'],
      status: 'active',
      defaultFailurePolicy: 'halt',
      scheduler: { leaseOwner: 'demo-scheduler', lastTickAt: NOW },
      createdAt: NOW,
      updatedAt: NOW,
    },
    nodes: [
      ...SPECS.map((spec) => ({
        id: spec.nodeId,
        graphId: GRAPH_ID,
        kind: 'backlog' as const,
        backlogItemId: spec.id,
        tags: spec.tags.filter((tag) => tag !== 'epic-demo').slice(0, 3),
        status: spec.nodeStatus,
        ...(spec.familyId ? { currentFamilyId: spec.familyId } : {}),
        ...(spec.rootRunId ? { currentRootRunId: spec.rootRunId } : {}),
        ...(spec.latestRunId ? { latestRunId: spec.latestRunId } : {}),
        ...(spec.baseRef ? { baseRef: spec.baseRef } : {}),
        ...(spec.upstreamBaseNodeIds ? { upstreamBaseNodeIds: spec.upstreamBaseNodeIds } : {}),
        waitingOn: spec.waitingOn ?? [],
        updatedAt: NOW,
      })),
      ...REFERENCE_NODES,
    ],
    edges: [
      {
        id: 'we_refine_to_contract',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_refine_requirement',
        toNodeId: 'wn_shared_contract',
        condition: { kind: 'family-done', outcome: 'success' },
        required: true,
        status: 'satisfied',
        unlock: { kind: 'mark-ready' },
        evidence: { observedAt: NOW, prNumber: 150, mergeSha: '3c76f96' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_contract_to_gateway',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_shared_contract',
        toNodeId: 'wn_gateway_projection',
        condition: { kind: 'family-done', outcome: 'success' },
        required: true,
        status: 'satisfied',
        unlock: { kind: 'enqueue' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_contract_to_ui_start',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_shared_contract',
        toNodeId: 'wn_ui_visualization',
        condition: { kind: 'family-done', outcome: 'success' },
        required: true,
        status: 'satisfied',
        unlock: { kind: 'mark-ready' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_contract_to_companion_start',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_shared_contract',
        toNodeId: 'wn_companion_status',
        condition: { kind: 'family-done', outcome: 'success' },
        required: true,
        status: 'satisfied',
        unlock: { kind: 'mark-ready' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_gateway_to_ui_rebase',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_gateway_projection',
        toNodeId: 'wn_ui_visualization',
        condition: { kind: 'merged', targetRef: 'main' },
        blocks: 'completion',
        required: true,
        status: 'pending',
        unlock: { kind: 'rebase-onto', flow: 'merge-main' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_gateway_to_companion_rebase',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_gateway_projection',
        toNodeId: 'wn_companion_status',
        condition: { kind: 'merged', targetRef: 'main' },
        blocks: 'completion',
        required: true,
        status: 'pending',
        unlock: { kind: 'rebase-onto', flow: 'merge-main' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_gateway_to_cli_start',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_gateway_projection',
        toNodeId: 'wn_cli_import',
        condition: { kind: 'family-done', outcome: 'success' },
        required: true,
        status: 'pending',
        unlock: { kind: 'enqueue' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_external_pr_to_companion_completion',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_external_core_pr',
        toNodeId: 'wn_companion_status',
        condition: { kind: 'reference-status', status: 'satisfied' },
        blocks: 'completion',
        required: true,
        status: 'pending',
        unlock: { kind: 'rebase-onto', flow: 'merge-main' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_package_to_release',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_package_publish',
        toNodeId: 'wn_release',
        condition: { kind: 'reference-status', status: 'satisfied' },
        required: true,
        status: 'satisfied',
        unlock: { kind: 'mark-ready' },
        evidence: {
          observedAt: NOW,
          referenceStatus: 'satisfied',
          referenceRef: '@metamask/controller@12.4.0',
        },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_ui_to_authoring_ux_gate',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_ui_visualization',
        toNodeId: 'wn_authoring_controls',
        condition: { kind: 'manual', gateId: 'ux-review' },
        required: true,
        status: 'pending',
        unlock: { kind: 'mark-ready' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_cli_to_e2e',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_cli_import',
        toNodeId: 'wn_e2e_validation',
        condition: { kind: 'family-done', outcome: 'success' },
        required: true,
        status: 'pending',
        unlock: { kind: 'mark-ready' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_authoring_to_e2e',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_authoring_controls',
        toNodeId: 'wn_e2e_validation',
        condition: { kind: 'manual', gateId: 'authoring-accepted' },
        required: true,
        status: 'pending',
        unlock: { kind: 'mark-ready' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_companion_to_e2e',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_companion_status',
        toNodeId: 'wn_e2e_validation',
        condition: { kind: 'family-done', outcome: 'success' },
        required: true,
        status: 'pending',
        unlock: { kind: 'mark-ready' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_e2e_to_release',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_e2e_validation',
        toNodeId: 'wn_release',
        condition: { kind: 'manual', gateId: 'operator-evidence-acceptance' },
        required: true,
        status: 'pending',
        unlock: { kind: 'mark-ready' },
        lastEvaluatedAt: NOW,
      },
      {
        id: 'we_docs_to_release',
        graphId: GRAPH_ID,
        fromNodeId: 'wn_docs',
        toNodeId: 'wn_release',
        condition: { kind: 'manual', gateId: 'docs-review' },
        required: true,
        status: 'waived',
        unlock: { kind: 'mark-ready' },
        evidence: {
          observedAt: NOW,
          manualResolution: {
            graphId: GRAPH_ID,
            gateId: 'docs-review',
            edgeId: 'we_docs_to_release',
            reason: 'Docs can be reviewed from the screenshot fixture before implementation ships.',
            decision: 'waived',
            resolvedAt: NOW,
          },
        },
        lastEvaluatedAt: NOW,
      },
    ],
    gates: [
      {
        graphId: GRAPH_ID,
        gateId: 'docs-review',
        edgeId: 'we_docs_to_release',
        reason: 'Docs can be reviewed from the screenshot fixture before implementation ships.',
        decision: 'waived',
        resolvedAt: NOW,
      },
    ],
    ledger: [
      {
        key: 'wg_demo_cross_project_epic:wn_cli_import:enqueue:v1',
        graphId: GRAPH_ID,
        nodeId: 'wn_cli_import',
        actionKind: 'enqueue',
        readinessVersion: 'v1',
        status: 'started',
        startedAt: NOW,
        result: 'Queued CLI import after gateway projection prerequisites were met.',
      },
    ],
  },
];
