import { StyleSheet } from 'react-native';

import { colors, fonts, radii, spacing } from '../../../lib/theme';
export const artifactViewerStyles = StyleSheet.create({
  center: { justifyContent: 'center', alignItems: 'center' },
  listContent: { padding: spacing.xl, paddingBottom: spacing.xxxl * 2 },
  stickyWorkspaceChrome: {
    backgroundColor: colors.bgSurface,
    borderBottomColor: colors.bgCard,
    borderBottomWidth: 1,
    elevation: 10,
    left: 0,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    position: 'absolute',
    right: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    top: 0,
    zIndex: 20,
  },
  artifactCell: { marginBottom: spacing.md },
  artifactCellLeft: { marginRight: spacing.md },
  header: { marginBottom: spacing.lg },
  primaryWorkspaceNavBlock: {
    marginTop: spacing.lg,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flowBadge: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 4,
  },
  flowText: { fontSize: fonts.sizeSm, fontWeight: '600' },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  countText: { color: colors.textMuted, fontSize: fonts.sizeSm },
  refreshButton: {
    backgroundColor: colors.bgInput,
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  refreshButtonDisabled: { opacity: 0.6 },
  refreshButtonText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  ticketText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeLg,
    fontWeight: '700',
    marginTop: spacing.md,
  },
  beforeAfterPriorityPanel: {
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  beforeAfterPriorityActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  beforeAfterPriorityCopy: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  beforeAfterPriorityButton: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  beforeAfterPriorityButtonText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  beforeAfterPriorityRail: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  contextCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: 16,
    borderWidth: 1,
    gap: spacing.md,
    marginTop: spacing.lg,
    padding: spacing.md,
  },
  contextHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  contextEyebrow: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  contextStatusBadge: {
    backgroundColor: colors.statusOk + '22',
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  contextStatusText: {
    color: colors.statusOk,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  contextGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  contextMetric: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    padding: spacing.md,
  },
  contextMetricDisabled: {
    opacity: 0.48,
  },
  contextMetricLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  contextMetricValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  artifactCockpitPanel: {
    backgroundColor: colors.bgCard,
    borderColor: colors.accent + '33',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginTop: spacing.md,
    padding: spacing.sm,
  },
  artifactCockpitHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  artifactCockpitTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  artifactCockpitTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  artifactCockpitMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  artifactCockpitPill: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  artifactCockpitPillText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  artifactCockpitRail: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  artifactCockpitTile: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    minWidth: 104,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  artifactCockpitTileActive: {
    backgroundColor: colors.accent + '18',
    borderColor: colors.accent + '66',
  },
  artifactCockpitTileLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  artifactCockpitTileLabelActive: {
    color: colors.accent,
  },
  artifactCockpitTileValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  artifactCockpitTileHint: {
    color: colors.textMuted,
    fontSize: 10,
    marginTop: 2,
    maxWidth: 110,
  },
  artifactProgressPanel: {
    marginTop: spacing.lg,
  },
  artifactCockpitDisabled: {
    opacity: 0.45,
  },
  focusedArtifactPanel: {
    backgroundColor: colors.accent + '12',
    borderColor: colors.accent + '55',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  focusedArtifactHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  focusedArtifactTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  focusedArtifactEyebrow: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  focusedArtifactPath: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
    lineHeight: 18,
    marginTop: spacing.xs,
  },
  focusedArtifactMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
  },
  focusedArtifactTypeBadge: {
    backgroundColor: colors.bgInput,
    borderColor: colors.accent + '44',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  focusedArtifactTypeText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  focusedArtifactActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  focusedArtifactAction: {
    backgroundColor: colors.accent + '20',
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  focusedArtifactActionDisabled: {
    opacity: 0.45,
  },
  focusedArtifactActionText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  focusedArtifactClear: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  focusedArtifactClearText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  recipePicker: {
    backgroundColor: colors.bgCard,
    borderRadius: 16,
    gap: spacing.sm,
    marginTop: spacing.lg,
    padding: spacing.md,
  },
  recipePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  recipePickerTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  recipePickerHint: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
  },
  recipeChip: {
    borderWidth: 1,
    borderColor: colors.bgInput,
    borderRadius: 14,
    marginRight: spacing.sm,
    minWidth: 136,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  recipeChipActive: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent,
  },
  recipeChipText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  recipeChipTextActive: {
    color: colors.accent,
  },
  recipeChipMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: spacing.xxl,
    marginBottom: spacing.md,
  },
  stickyFilter: {
    backgroundColor: colors.bgBase,
    borderWidth: 1,
    borderBottomColor: colors.bgCard,
    borderColor: colors.bgCard,
    borderRadius: 16,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    marginBottom: spacing.lg,
    gap: spacing.sm,
  },
  stickyFilterCompact: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    marginBottom: spacing.sm,
    paddingBottom: spacing.sm,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  stickyFilterCompactRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  stickyFilterCompactChips: {
    paddingRight: spacing.sm,
  },
  stickyFilterCompactCount: {
    color: colors.textMuted,
    flexShrink: 0,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  stickyFilterCompactQuery: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '700',
  },
  filterTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    fontWeight: '900',
  },
  filterCount: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  filterChip: {
    borderWidth: 1,
    borderColor: colors.textMuted + '55',
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    marginRight: spacing.sm,
  },
  filterChipCompact: {
    marginRight: 0,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
  },
  filterChipActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accent + '22',
  },
  filterText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  filterTextCompact: {
    fontSize: 11,
  },
  filterTextActive: {
    color: colors.accent,
  },
  focusedFilterPill: {
    alignItems: 'center',
    backgroundColor: colors.bgInput,
    borderColor: colors.accent + '55',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  focusedFilterText: {
    color: colors.textSecondary,
    flex: 1,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  focusedFilterClear: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: fonts.sizeSm,
    padding: spacing.xl,
    textAlign: 'center',
  },
  errorText: {
    color: colors.statusFail,
    fontSize: fonts.sizeSm,
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.lg,
  },
});
