import { StyleSheet } from 'react-native';

import { colors, fonts, radii, spacing } from '../../../lib/theme';

export const familyWorkspaceStyles = StyleSheet.create({
  center: { justifyContent: 'center', alignItems: 'center', padding: spacing.xl },
  backFallbackButton: {
    backgroundColor: colors.accent + '20',
    borderRadius: radii.md,
    marginTop: spacing.lg,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
  },
  backFallbackText: {
    color: colors.accent,
    fontSize: fonts.sizeSm,
    fontWeight: '800',
  },
  scrollContent: { padding: spacing.xl, paddingBottom: spacing.xxxl * 2 },
  stickyWorkspaceNav: {
    backgroundColor: colors.bgSurface,
    borderBottomColor: colors.bgCard,
    borderBottomWidth: 1,
    left: 0,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 20,
  },
  headerCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.lg,
    gap: spacing.md,
    marginBottom: spacing.xl,
    padding: spacing.xl,
  },
  headerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  statusBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  statusText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  generatedText: { color: colors.textMuted, fontSize: fonts.sizeXs },
  title: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXl,
    fontWeight: '900',
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  metricItem: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.md,
    flexGrow: 1,
    minWidth: 120,
    padding: spacing.md,
  },
  metricItemCompact: {
    minWidth: 82,
    padding: spacing.sm,
  },
  metricLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  metricValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
    marginTop: spacing.xs,
  },
  familyCockpit: {
    backgroundColor: colors.bgCard,
    borderColor: colors.accent + '33',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginBottom: spacing.xl,
    padding: spacing.sm,
  },
  familyCockpitHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  familyCockpitTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  familyCockpitTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  familyCockpitMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  familyCockpitRail: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  familyCockpitTile: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    minWidth: 104,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  familyCockpitTileLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  familyCockpitTileValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  familyCockpitTileHint: {
    color: colors.textMuted,
    fontSize: 10,
    marginTop: 2,
    maxWidth: 110,
  },
  familyCockpitAction: {
    backgroundColor: colors.accent + '14',
    borderColor: colors.accent + '44',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  familyCockpitActionPrimary: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
  },
  familyCockpitActionText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  familyCockpitActionTextPrimary: {
    color: colors.textPrimary,
  },
  familyCockpitDisabled: {
    opacity: 0.45,
  },
  familyFocusedArtifactCard: {
    backgroundColor: colors.accent + '12',
    borderColor: colors.accent + '55',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginBottom: spacing.xl,
    padding: spacing.sm,
  },
  familyFocusedArtifactEyebrow: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  familyFocusedArtifactPath: {
    color: colors.textPrimary,
    fontFamily: fonts.mono,
    fontSize: fonts.sizeSm,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  familyFocusedArtifactMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
    textTransform: 'uppercase',
  },
  familyBeforeAfterPriorityPanel: {
    backgroundColor: colors.accent + '10',
    borderColor: colors.accent + '44',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    marginBottom: spacing.xl,
    padding: spacing.sm,
  },
  familyBeforeAfterPriorityActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  familyBeforeAfterPriorityCopy: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  familyBeforeAfterPriorityButton: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  familyBeforeAfterPriorityButtonText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  familyBeforeAfterPriorityRail: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  section: { marginBottom: spacing.xl },
  focusRunCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    marginBottom: spacing.xl,
    padding: spacing.lg,
  },
  focusRunCardActive: {
    borderColor: colors.accent,
  },
  focusRunHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  focusRunSelectButton: {
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  focusRunSelectText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  focusRunTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeLg,
    fontWeight: '900',
  },
  focusRunMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  focusEvidenceBox: {
    backgroundColor: colors.bgInput,
    borderColor: colors.accent + '33',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  focusEvidenceHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  focusEvidenceTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  focusEvidenceTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  focusEvidenceMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
  },
  focusEvidenceOpenButton: {
    backgroundColor: colors.accent + '20',
    borderColor: colors.accent + '55',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  focusEvidenceOpenText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  focusEvidenceStrip: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  focusEvidenceItem: {
    flex: 1,
    minWidth: 0,
  },
  focusEvidenceImage: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.sm,
    height: 72,
    width: '100%',
  },
  focusEvidenceDoc: {
    alignItems: 'center',
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.sm,
    borderWidth: 1,
    height: 72,
    justifyContent: 'center',
  },
  focusEvidenceDocType: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  focusEvidencePath: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
  },
  focusEvidenceDocRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  focusEvidenceDocChip: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    maxWidth: 180,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  focusEvidenceDocChipText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  focusEvidenceMoreButton: {
    alignSelf: 'flex-start',
  },
  focusEvidenceMoreText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  focusRetroBox: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.md,
    gap: spacing.sm,
    padding: spacing.md,
  },
  focusRetroHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  focusRetroLabel: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  focusRetroText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    lineHeight: 20,
  },
  recipeQualityBox: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  recipeQualityLabel: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  recipeQualityList: {
    gap: spacing.xs,
  },
  recipeQualityGuidance: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    gap: spacing.xs,
    padding: spacing.sm,
  },
  recipeQualityGuidanceTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  recipeQualityText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    lineHeight: 16,
  },
  recipeQualityFindings: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  familyDecisionPanel: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  familyDecisionTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  familyDecisionCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderLeftWidth: 3,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  familyDecisionBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  familyDecisionBadgeText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  familyDecisionCardTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  familyDecisionSummary: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    lineHeight: 18,
  },
  familyDecisionChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  familyDecisionChip: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.sm,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  familyDecisionChipText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  focusRetroMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
    letterSpacing: 0.5,
    marginBottom: spacing.md,
    textTransform: 'uppercase',
  },
  sectionMeta: { color: colors.textMuted, fontSize: fonts.sizeXs },
  compactOpenButton: {
    backgroundColor: colors.accent + '18',
    borderColor: colors.accent + '55',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  compactOpenText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  ledgerMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.md,
    marginTop: spacing.sm,
  },
  ledgerEntries: {
    gap: spacing.sm,
  },
  ledgerEntryCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  ledgerEntryHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  ledgerEntryTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  ledgerEntryTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  ledgerEntryMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  ledgerEntryPr: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  ledgerEntryFacts: {
    gap: spacing.xs,
  },
  ledgerFact: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
  },
  ledgerMissing: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  ledgerMoreText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    marginTop: spacing.sm,
  },
  comparePairCard: {
    marginRight: spacing.md,
    width: 320,
  },
  comparePairActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  comparePairAction: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  comparePairActionText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textAlign: 'center',
  },
  compareMoreText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    marginTop: spacing.sm,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  filterChip: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgInput,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  filterChipActive: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
  },
  filterChipText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  filterChipTextActive: {
    color: colors.accent,
  },
  evidenceNote: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    lineHeight: 17,
    marginBottom: spacing.md,
  },
  errorText: {
    color: colors.statusFail,
    fontSize: fonts.sizeSm,
    marginBottom: spacing.lg,
  },
  retroCard: {
    backgroundColor: colors.statusWarn + '14',
    borderColor: colors.statusWarn + '55',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    marginBottom: spacing.md,
    padding: spacing.lg,
  },
  retroHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  retroRun: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  retroStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
  },
  retroStatusText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  retroTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    fontWeight: '900',
  },
  retroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  retroMeta: { color: colors.textMuted, fontSize: fonts.sizeXs },
  retroEvidencePath: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  retroEvidencePreview: {
    backgroundColor: colors.bgInput,
    borderColor: colors.statusWarn + '33',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  retroEvidencePreviewHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  retroEvidencePreviewTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  retroEvidencePreviewOpen: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  retroSignalRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  retroSignalChip: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.sm,
    minWidth: 82,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  retroSignalChipPressable: {
    borderColor: colors.statusWarn + '55',
    borderWidth: 1,
  },
  retroSignalLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  retroSignalValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    marginTop: 2,
  },
  retroActionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.xs,
    paddingRight: spacing.md,
  },
  retroActionButton: {
    borderColor: colors.statusWarn + '55',
    borderRadius: radii.md,
    borderWidth: 1,
    minWidth: 104,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  retroActionButtonPrimary: {
    backgroundColor: colors.statusWarn + '22',
  },
  retroActionText: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  retroActionTextPrimary: {
    color: colors.textPrimary,
  },
  retroActionValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  runCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCard,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    marginBottom: spacing.md,
    padding: spacing.lg,
  },
  runCardActive: {
    borderColor: colors.accent,
  },
  runTitleBlock: { flex: 1, minWidth: 0 },
  runTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    fontWeight: '900',
  },
  runStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  runStatusText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  runMetaGrid: { flexDirection: 'row', gap: spacing.sm },
  runCardComparePreview: {
    backgroundColor: colors.bgInput,
    borderColor: colors.accent + '24',
    borderRadius: radii.lg,
    borderWidth: 1,
    padding: spacing.xs,
  },
  runActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  inlineButton: {
    backgroundColor: colors.accent + '20',
    borderColor: colors.accent + '55',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  inlineButtonText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  inlineButtonActive: {
    backgroundColor: colors.statusOk + '20',
    borderColor: colors.statusOk + '66',
  },
  inlineButtonTextActive: {
    color: colors.statusOk,
  },
  reviewButton: {
    backgroundColor: colors.statusWarn + '20',
    borderColor: colors.statusWarn + '66',
  },
  reviewButtonText: {
    color: colors.statusWarn,
  },
  artifactGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  artifactCell: {
    marginBottom: spacing.md,
  },
  artifactWorkspaceButton: {
    alignItems: 'center',
    backgroundColor: colors.accent + '18',
    borderColor: colors.accent + '44',
    borderRadius: radii.sm,
    borderWidth: 1,
    marginTop: spacing.xs,
    paddingVertical: spacing.xs,
  },
  artifactWorkspaceText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  evidenceGroupCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    marginBottom: spacing.lg,
    padding: spacing.md,
  },
  carriedGroupCard: {
    borderColor: colors.statusWarn + '55',
  },
  evidenceGroupHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  evidenceGroupTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  evidenceGroupTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  evidenceGroupMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
  },
  evidenceGroupHeaderActions: {
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  evidenceGroupCount: {
    backgroundColor: colors.bgInput,
    borderRadius: 999,
    color: colors.textSecondary,
    fontFamily: fonts.mono,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  evidenceGroupWorkspaceButton: {
    backgroundColor: colors.accent + '18',
    borderColor: colors.accent + '44',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  evidenceGroupWorkspaceText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  artifactKindRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  artifactKindText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  artifactKindBefore: {
    color: colors.statusWarn,
  },
  artifactKindAfter: {
    color: colors.statusOk,
  },
  artifactKindSetup: {
    color: colors.textMuted,
  },
  artifactRunText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  evidenceGroupMoreButton: {
    alignSelf: 'flex-start',
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  evidenceGroupMore: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  evidenceGroupActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  learningCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    gap: spacing.sm,
    marginBottom: spacing.md,
    padding: spacing.lg,
  },
  learningTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    fontWeight: '900',
  },
});
