import { StyleSheet } from 'react-native';

import { colors, fonts, radii, spacing } from '../../../lib/theme';

export const slotWorkspaceStyles = StyleSheet.create({
  center: { justifyContent: 'center', alignItems: 'center' },
  scrollContent: { padding: spacing.xl, paddingBottom: spacing.xxxl * 2 },
  stickyWorkspaceNav: {
    backgroundColor: colors.bgSurface,
    borderBottomColor: colors.bgCard,
    borderBottomWidth: 1,
    left: 0,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.sm,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 20,
  },
  headerCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.lg,
    padding: spacing.xl,
    marginBottom: spacing.xl,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  slotName: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXl,
    fontWeight: '700',
  },
  badge: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 4,
  },
  badgeText: { fontSize: fonts.sizeSm, fontWeight: '600' },
  section: {
    marginBottom: spacing.xl,
  },
  errorText: {
    color: colors.statusFail,
    fontSize: fonts.sizeSm,
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: spacing.md,
  },
  healthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  healthItem: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    padding: spacing.lg,
    minWidth: 90,
    alignItems: 'center',
  },
  healthLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginBottom: spacing.xs,
    textTransform: 'uppercase',
  },
  healthValue: {
    fontSize: fonts.sizeSm,
    fontWeight: '600',
  },
  infoRow: { gap: spacing.sm },
  workspaceCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.lg,
  },
  readyWorkspaceCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.statusOk + '44',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  focusedArtifactCard: {
    backgroundColor: colors.accent + '12',
    borderColor: colors.accent + '55',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  focusedArtifactTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  focusedArtifactEyebrow: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  focusedArtifactPath: {
    color: colors.textPrimary,
    fontFamily: fonts.mono,
    fontSize: fonts.sizeSm,
    fontWeight: '800',
    marginTop: spacing.xs,
  },
  focusedArtifactMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
    textTransform: 'uppercase',
  },
  workspaceBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  workspaceBadgeText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  workspaceFocusBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  workspaceFocusText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  workspaceCurrentButton: {
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  workspaceCurrentText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  workspaceMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeLg,
    fontWeight: '900',
  },
  workspaceMetricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  workspaceMetricRail: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  workspaceMetric: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.md,
    flexGrow: 1,
    minWidth: 92,
    padding: spacing.md,
  },
  workspaceMetricCompact: {
    flexGrow: 0,
    minWidth: 112,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  workspaceMetricLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  workspaceMetricValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
    marginTop: spacing.xs,
  },
  cockpitPanel: {
    backgroundColor: colors.bgInput,
    borderColor: colors.accent + '30',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  slotCompareFocusPanel: {
    backgroundColor: colors.accent + '10',
    borderColor: colors.accent + '66',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  slotBeforeAfterPriorityPanel: {
    backgroundColor: colors.accent + '10',
    borderColor: colors.accent + '44',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  slotBeforeAfterPriorityActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  slotBeforeAfterPriorityCopy: {
    color: colors.textMuted,
    flex: 1,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  slotBeforeAfterPriorityButton: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  slotBeforeAfterPriorityButtonText: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  slotBeforeAfterPriorityRail: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  cockpitHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  cockpitTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  cockpitMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
    textTransform: 'uppercase',
  },
  cockpitTerminalButton: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  cockpitTerminalText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  cockpitRail: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  cockpitTile: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    minWidth: 104,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  cockpitTileDisabled: {
    opacity: 0.45,
  },
  cockpitTileLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  cockpitTileValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  cockpitTileHint: {
    color: colors.textMuted,
    fontSize: 10,
    marginTop: 2,
    maxWidth: 110,
  },
  pendingDecisionBlock: {
    gap: spacing.sm,
  },
  workspaceFocusedGateBlock: {
    gap: spacing.sm,
  },
  workspaceFocusedGateTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  slotDiffFocusPanel: {
    backgroundColor: colors.accent + '10',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  slotMissingGateFocusPanel: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  slotTerminalFocusPanel: {
    backgroundColor: colors.lifecycleWorking + '10',
    borderColor: colors.lifecycleWorking + '66',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  slotRetroFocusPanel: {
    backgroundColor: colors.statusWarn + '10',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  slotRetroFocusTitleBlock: {
    flex: 1,
    gap: spacing.sm,
  },
  slotRetroVisualPreview: {
    marginTop: spacing.xs,
  },
  workspaceGateCard: {
    backgroundColor: colors.statusWarn + '10',
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  workspaceGateList: {
    gap: spacing.md,
  },
  workspaceGateHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  workspaceGateStatusWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  workspaceGateStatus: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceGateBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  workspaceGateBadgeText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceGateOpenButton: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  workspaceGateOpenText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  workspaceGateTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  workspaceGateSummary: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    lineHeight: 19,
  },
  workspaceGateEvidence: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '800',
  },
  workspaceGateEvidenceList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  workspaceGateEvidenceChip: {
    backgroundColor: colors.bgInput,
    borderColor: colors.accent + '44',
    borderRadius: 999,
    borderWidth: 1,
    maxWidth: 160,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  workspaceGateEvidenceChipText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  workspaceGatePreviewStrip: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  pendingDecisionTitle: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  pendingDecisionCard: {
    alignItems: 'center',
    backgroundColor: colors.statusWarn + '14',
    borderColor: colors.statusWarn + '55',
    borderRadius: radii.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  pendingDecisionText: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: fonts.sizeSm,
    fontWeight: '800',
  },
  pendingDecisionCta: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  decisionSignalsPanel: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  decisionSignalCard: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderLeftWidth: 3,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.md,
  },
  decisionSignalBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  decisionSignalBadgeText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  decisionSignalSummary: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    lineHeight: 18,
  },
  decisionSignalChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  decisionSignalChip: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.sm,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  decisionSignalChipText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  recipeEvidencePanel: {
    backgroundColor: colors.accent + '14',
    borderColor: colors.accent + '55',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  runEvidencePanel: {
    backgroundColor: colors.statusOk + '12',
    borderColor: colors.statusOk + '44',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  familyContextPanel: {
    backgroundColor: colors.statusWarn + '10',
    borderColor: colors.statusWarn + '44',
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.sm,
  },
  familyContextOpenButton: {
    borderColor: colors.statusWarn + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  familyContextOpenText: {
    color: colors.statusWarn,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  familyContextRail: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  familyContextMetric: {
    backgroundColor: colors.bgInput,
    borderColor: colors.statusWarn + '22',
    borderRadius: radii.md,
    borderWidth: 1,
    minWidth: 112,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  familyContextMetricDisabled: {
    opacity: 0.55,
  },
  familyContextMetricLabel: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  familyContextMetricValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  familyRetroSignalList: {
    gap: spacing.sm,
  },
  familyRetroSignalCard: {
    backgroundColor: colors.bgInput,
    borderRadius: radii.md,
    borderWidth: 1,
    gap: spacing.xs,
    padding: spacing.md,
  },
  familyRetroSignalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  familyRetroStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  familyRetroStatusText: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  familyRetroTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  familyRetroMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
  },
  familyRetroVisualPreview: {
    marginTop: spacing.xs,
  },
  familyRetroSignalActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  familyRetroSignalAction: {
    backgroundColor: colors.bgCard,
    borderColor: colors.bgCardHover,
    borderRadius: radii.sm,
    borderWidth: 1,
    minWidth: 78,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  familyRetroSignalActionLabel: {
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  familyRetroSignalActionValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    marginTop: 1,
  },
  runEvidenceOpenButton: {
    borderColor: colors.statusOk + '66',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  runEvidenceOpenText: {
    color: colors.statusOk,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  recipeEvidenceHeaderActions: {
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  recipeEvidenceOpenButton: {
    borderColor: colors.accent + '77',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  recipeEvidenceOpenText: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  runEvidenceEmptyText: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    lineHeight: 17,
  },
  recipeEvidenceTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  recipeEvidenceMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
    textTransform: 'uppercase',
  },
  recipeEvidenceSelected: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  recipePreviewStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  recipePreviewButton: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgCardHover,
    borderRadius: radii.md,
    borderWidth: 1,
    overflow: 'hidden',
  },
  recipeRunPickerHeader: {
    gap: spacing.xs,
  },
  recipeRunPickerTitle: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  recipeRunPickerHint: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
  },
  recipePreviewImage: {
    backgroundColor: colors.bgInput,
    height: 56,
    width: 76,
  },
  runEvidenceDocumentTile: {
    alignItems: 'center',
    backgroundColor: colors.bgInput,
    gap: spacing.xs,
    height: 56,
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    width: 86,
  },
  runEvidenceDocumentKind: {
    color: colors.accent,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  runEvidenceDocumentPath: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    lineHeight: 14,
    textAlign: 'center',
  },
  recipeRunChip: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgInput,
    borderRadius: radii.md,
    borderWidth: 1,
    marginRight: spacing.sm,
    minWidth: 144,
    padding: spacing.md,
  },
  recipeRunChipActive: {
    backgroundColor: colors.accent + '20',
    borderColor: colors.accent,
  },
  recipeRunChipHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  recipeRunStatus: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  recipeRunPromoted: {
    color: colors.statusOk,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
  },
  recipeRunChipTitle: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    marginTop: spacing.xs,
  },
  recipeRunChipTitleActive: {
    color: colors.accent,
  },
  recipeRunChipMeta: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    marginTop: spacing.xs,
    textTransform: 'uppercase',
  },
  workspaceActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  workspaceActionButton: {
    backgroundColor: colors.bgInput,
    borderColor: colors.bgInput,
    borderRadius: radii.md,
    borderWidth: 1,
    minWidth: 104,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  workspaceActionButtonPrimary: {
    backgroundColor: colors.accent + '22',
    borderColor: colors.accent + '66',
  },
  workspaceActionButtonDisabled: {
    opacity: 0.45,
  },
  workspaceActionText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceActionTextPrimary: {
    color: colors.accent,
  },
  workspaceActionValue: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: '900',
  },
  recentRunsBlock: {
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  recentRunsTitle: {
    color: colors.textMuted,
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  historyRunCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    gap: spacing.md,
    padding: spacing.lg,
  },
  historyComparePreview: {
    backgroundColor: colors.bgInput,
    borderColor: colors.accent + '24',
    borderRadius: radii.lg,
    borderWidth: 1,
    padding: spacing.xs,
  },
  historyRunTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  historyRunTitle: {
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    fontWeight: '900',
  },
  historyRunStatus: {
    fontSize: fonts.sizeXs,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  phaseCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radii.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  phaseName: {
    color: colors.textPrimary,
    fontSize: fonts.sizeMd,
    fontWeight: '600',
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.sm,
    paddingLeft: spacing.md,
  },
  stepIcon: {
    color: colors.statusOk,
    fontSize: fonts.sizeSm,
    width: 16,
  },
  stepName: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    flex: 1,
  },
});
